name: Build nmqttgui

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          #- windows-latest
          #- macOS-latest
        version:
          - 1.2.0
    
    steps:
    - uses: actions/checkout@v1
    - uses: jiro4989/setup-nim-action@master
      with:
        nim-version: ${{ matrix.version }}
        
    - name: Foreign dep
      run: |
        sudo apt update
        sudo apt-get install gtk+-3.0 webkit2gtk-4.0 build-essential

    - name: Nimble Refresh
      run: nimble -y refresh
        
    - name: Nimble Install dependencies
      run: nimble -n install --depsOnly
      
    - name: Build project
      run: |
        nimble build -d:release
        mkdir -p rel
        #mv bin/nmqtt rel/nmqtt
        #mv bin/nmqtt_password rel/nmqtt_password
        #mv bin/nmqtt_pub rel/nmqtt_pub
        #mv bin/nmqtt_sub rel/nmqtt_sub
        mv bin/nmqttgui rel/nmqttgui
      
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: release-${{ matrix.os }}
        path: rel
